#ifndef _FUNCONFIG_H
#define _FUNCONFIG_H

#define FUNCONF_USE_HSI 1
#define FUNCONF_USE_HSE 0
#define CLK_SOURCE_CH5XX CLK_SOURCE_PLL_60MHz
#define FUNCONF_SYSTEM_CORE_CLOCK 60000000 // 60MHz

#define FUNCONF_DEBUG_HARDFAULT 0
#define FUNCONF_USE_CLK_SEC 0
#define FUNCONF_USE_DEBUGPRINTF 0

#endif
