all : flash

TARGET:=drv8835controller
TARGET_MCU:=CH572

MINICHLINK:=../../../antigravity-mounriver/tools
include ../../ch32fun/ch32fun.mk

# bootloader :
# 	./$(TARGET).py -b

flash : cv_flash
clean : cv_clean
