
import json
import time

def create_netscape_cookie_file(json_file, output_file):
    try:
        with open(json_file, 'r') as f:
            data = json.load(f)
        
        cookie_header = data.get('cookie', '')
        if not cookie_header:
            print("No 'cookie' field found in json.")
            return

        with open(output_file, 'w') as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# This file is generated by mp3_sync based on oauth.json headers\n\n")
            
            # Helper to write a line
            def write_cookie(name, value, domain=".youtube.com"):
                # Expires in 1 year
                expiry = int(time.time()) + 31536000 
                f.write(f"{domain}\tTRUE\t/\tTRUE\t{expiry}\t{name}\t{value}\n")
                # Also write for .google.com just in case
                f.write(f".google.com\tTRUE\t/\tTRUE\t{expiry}\t{name}\t{value}\n")

            # Simple parsing of "Key=Value; Key2=Value2"
            parts = cookie_header.split(';')
            for part in parts:
                if '=' in part:
                    name, value = part.strip().split('=', 1)
                    write_cookie(name, value)
        
        print(f"Successfully created {output_file}")
            
    except Exception as e:
        print(f"Error creating cookie file: {e}")

if __name__ == "__main__":
    create_netscape_cookie_file('oauth.json', 'cookies.txt')
